### ISSUE TITLE
Incorrect messages when choose to visualize only public repos

### ISSUE THREAD

**Issue by nayaramoura** [TWtablero/tablero#141]
When we access the app we need to inform if we would like to see only the public repos or if we want to see publics repo too.

Choosing to see only public, We get 2 failures:
1) The message "Oops..." is displayed.
2) When we click in the OK button, the message box don't close.

**Comment by enzoz** [comment]
This bug is not happening anymore and I'm going to close the issue.
If it happen again we can reopen this.
