### ISSUE TITLE
Allow the creation of new columns

### ISSUE THREAD

**Issue by lqust** [TWtablero/tablero#144]
Columns should be based on labels, so they are dynamic.

Example:
1 - Analysis
2 - Dev
3 - Test

I can add another column by changing to:
1 - Analysis
2 - Dev
3 - Desk check
4 - Test

**Comment by rodrigomaia17** [comment]
Ei @enzoz , how are you planning to do this implementation? Come talk to me! (:

**Comment by flmmartins** [comment]
Waiting for @rodrigomaia17 to put this as done.

**Comment by flmmartins** [comment]
Rodrigo approved... more tests are necessary,,

**Comment by rodrigomaia17** [comment]
@flmmartins We also need to add these new columns informations on read.me
