### ISSUE TITLE
Differentiate pull requests on exports

### ISSUE THREAD

**Issue by lqust** [TWtablero/tablero#173]
*Why?*
Currently when I export to see the stories that are open, I see pull requests also. The export is used to do analysis and calculate lead time on stories, so pull requests are noise and need to be filtered out

*Definition of done*
I can see only stories on the export either because pull requests are not exported or because I was able to filter them out

**Comment by anikarni** [comment]
Pull requests are no longer shown in Tablero, so they will not show up on the CSV.

Thanks!
