### ISSUE TITLE
Cannot restrict permission requests to specific projects

### ISSUE THREAD

**Issue by alxndrsn** [TWtablero/tablero#181]
# Issue

I am interested in the Pixelated project, but to access the Tablero board for this project I must grant write access to all my public git repositories.  This is excessive, and puts me off getting further involved with a project whose primary focus is privacy.

# Desired behaviour

1. Allow/configure Tablero to only request access to *Issues* relating to a specific github project.
2. Do not request access to the following github features unless they are actually required:

    * Code
    * Pull requests
    * Wikis
    * Settings
    * Webhooks and services
    * Deploy keys

As I've not actually used Tablero yet (due to it's permission requests), I am not sure if any of these permissions are actually required.

**Comment by rodrigomaia17** [comment]
unfortunately the github does not provide a way to require only permissions to the Issues, or just to a specific repository. we not yet found a way around this problem. If you have a question or suggestion, let us know, give your opinion, or contribute! Transparency is essential for us
