### ISSUE TITLE
'+ CREATE ISSUE' button sets 0 - Backlog tag

### ISSUE THREAD

**Issue by lqust** [TWtablero/tablero#195]
### Steps to reproduce

1. Click on '+ CREATE ISSUE'
2. Write any content on issue
3. Click to create
4. Click to see newly created issue

### Expected result

Tag backlog is not present

### Actual result

Issue is tagged as '0 - Backlog'

**Comment by mnetto** [comment]
I'm closing this issue. All issues without column labels are displayed automagically on Backlog, also, there's an open issue to add labels via Tablero.
See also: #115, #119
