### ISSUE TITLE
Reloading the rocketboard displays all issues again, even if the project filter is still shown as activated

### ISSUE THREAD

**Issue by varac** [TWtablero/tablero#98]
I filtered for "pixelated-project-issues", which worked as expected. But after i reloaded the page, the filter still shows only that the pixelated-project-issues is active, but all issues from all projects are shown.
![screenshot](https://cloud.githubusercontent.com/assets/488213/5297306/b83a441e-7bad-11e4-818d-379e9080c57a.png)

see screenshot.

**Comment by mnetto** [comment]
Couldn't reproduce the error in dev environment. Production still has the bug?
